[project]
name = "workspace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.118.2",
    "fastapi-proxy-lib>=0.3.0",
    "uvicorn>=0.37.0",
]
